POST http://localhost:8000/business/confirm-order/do
Content-Type: application/json
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYmYiOjE3MzUwMjcyODcsIm1vYmlsZSI6IjEzOTU4ODU4MDU0IiwiaWQiOjE4NzAwODk2MjkxNzMxNTc4ODgsImV4cCI6MTczNTExMzY4NywiaWF0IjoxNzM1MDI3Mjg3fQ.derdSZRuS1GZ4C_yRqYsxST2Xpa5ItJjIdyHTPj1qIk

{
  "dailyTrainTicketId":1870094525343600640,
  "date":1735660800000,
  "end":"天津",
  "start":"北京",
  "tickets":[{
    "passengerId":1870094383295107072,
    "passengerIdCard":"1111",
    "passengerName":"蔡徐坤",
    "passengerType":"1",
    "seatTypeCode":"2"
  }],
  "trainCode":"G12"
}
###