server:
  port: 8000

# 路由转发，将/member/...的请求转发了member模块
spring:
  cloud:
    gateway:
      routes:
        - id: member
          predicates:
            - Path=/member/**
          uri: http://127.0.0.1:8001
        - id: business
          predicates:
            - Path=/business/**
          uri: http://127.0.0.1:8002
        - id: batch
          predicates:
            - Path=/batch/**
          uri: http://127.0.0.1:8003

      # 允许请求来源（老版本叫allowedOrigin）        跨域请求问题
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有路径

            # 是否允许携带cookie
            allowCredentials: true
            # 允许携带的头信息
            allowedHeaders: '*'
            # 允许的请求方式
            allowedMethods: '*'
            # 允许请求来源（老版本叫allowedOrigin）
            allowedOriginPatterns: '*'
            # 跨域检测的有效期，会发起一个OPTION请求
            maxAge: 3600