server:
  port: 8002
  servlet:
    context-path: /business

spring:
  application:
    name: business
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/train_business?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: train_business
    password: 123456qaq
  data:
    redis:
      host: localhost
      port: 6379
      database: 1
  cache:
    type: redis
    redis:
      use-key-prefix: true
      key-prefix: train_cache_
      cache-null-values: true
      time-to-live: 60s

# mybatis xml路径
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  logging.level.com.jiawa.train.business.mapper: trace
#  configuration:
#    local-cache-scope: statement #把一次会话生效的mybatis一级缓存改为statement级别(每句sql单独生效),即关闭一级缓存


